name: Deploy Node.js to cPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 
      - name: Install dependencies
        run: npm install
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /public_html/backend/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
      - name: Install dependencies and restart via SSH
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} \
          "cd ~/public_html/backend && npm install && npm run start"